// === USER
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const USER_IMAGES_REPOSITORY = 'USER_IMAGES_REPOSITORY';
export const USER_MAIN_IMAGE_REPOSITORY = 'USER_MAIN_IMAGE_REPOSITORY';
export const USER_BANNED = 'USER_BANNED';

// === POS
export const POST_REPOSITORY = 'POST_REPOSITORY';
export const POST_FILES_REPOSITORY = 'POST_FILES_REPOSITORY';
// === LIKE
export const LIKE_REPOSITORY = 'LIKE_REPOSITORY';
export const COMMENT_REPOSITORY = 'COMMENT_REPOSITORY';
export const CITY_REPOSITORY = 'CITY_REPOSITORY';
// === FRIEND
export const FRIEND_REPOSITORY = 'FRIEND_REPOSITORY';
export const REQUEST_REPOSITORY = 'REQUEST_REPOSITORY';

// === RESUME
export const VACANCY_REPOSITORY = 'VACANCY_REPOSITORY';
export const VACANCY_SKILLS = 'VACANCY_SKILLS';
export const RESUME_REPOSITORY = 'RESUME_REPOSITORY';
export const RESUME_SKILLS_REPOSITORY = 'RESUME_SKILLS_REPOSITORY';

// === 'DB
export const DB_REPOSITORY = 'DB_REPOSITORY';

// === CHAT
export const CHAT_REPOSITORY = 'CHAT_REPOSITORY';
export const CHAT_USER_REPOSITORY = 'CHAT_USER_REPOSITORY';

export const MESSAGE_REPOSITORY = 'MESSAGE_REPOSITORY';
export const MESSAGE_FILES_REPOSITORY = 'MESSAGE_FILES_REPOSITORY';
export const REPLY_MESSAGE = 'REPLY_MESSAGE';
export const MESSAGE_FILE = 'MESSAGE_FILE';
