export const USER_REPOSITORY = 'USER_REPOSITORY';
export const USER_IMAGES = 'USER_IMAGES';

export const POST_REPOSITORY = 'POST_REPOSITORY';
export const POST_FILES_REPOSITORY = 'POST_FILES_REPOSITORY';

export const LIKE_REPOSITORY = 'LIKE_REPOSITORY';
export const COMMENT_REPOSITORY = 'COMMENT_REPOSITORY';

export const DB_REPOSITORY = 'DB_REPOSITORY';
